# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]
        exclude:
          - os: macos-latest
            python-version: 3.9
        include:
          - os: windows-latest
            python-version: 3.8.10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: Run static analysis lint
      uses: pre-commit/action@v3.0.0
    - name: Prepare the API keys & Run pytest
      env:
        CLARIFAI_USER_EMAIL_SECURE_HOSTING: ${{ secrets.CLARIFAI_USER_EMAIL_SECURE_HOSTING }}
        CLARIFAI_USER_EMAIL: ${{ secrets.INTERNAL_USER_EMAIL }}
        CLARIFAI_USER_PASSWORD: ${{ secrets.INTERNAL_USER_PASSWORD }}
      shell: bash
      run: |
        export PYTHONPATH=.
        export CLARIFAI_USER_ID="$(python scripts/key_for_tests.py --get-userid)"
        export CLARIFAI_PAT="$(python scripts/key_for_tests.py --create-pat)"
        if [ "${{ github.event.pull_request.head.repo.full_name }}" = "${{ github.repository }}" ]; then
          pytest tests/
        else
          echo "Skipping tests for PRs from forks"
        fi
